version: 2

sources:
    - name: staging
      #For bigquery:
      database: dtc-de-zoomcamp-376519
      schema: temperatures

      tables:
        - name: temperatures_all
         # freshness:
           # error_after: {count: 6, period: hour}

models:
    - name: stg_measurments
      description: >
        Mean daily measurements.
        Table contains records of daily measurements. Values are totals, mean-averages, minima and maxima.
        Each measurement has a corresponding quality level, indicated by the suffix _qn3 and _qn4.
      columns:
        - name: measurement_id 
          description: placeholder
          data_type: string
          tests:
            - unique:
                severity: warn
            - not_null:
                severity: warn
        - name: station_id
          description: placeholder
          data_type: string
          tests:
            - not_null:
                severity: warn
        - name: dt_measurement
          description: placeholder
          data_type: timestamp
          tests:
            - not_null:
                severity: warn
        - name: quality_niveau_3
          description: placeholder
          data_type: integer
          tests:
            - accepted_values:
                values: [1, 2, 3, 5, 7, 8, 9, 10]
                quote: false
        - name: quality_niveau_4
          description: placeholder
          data_type: integer
          tests:
            - accepted_values:
                values: [1, 2, 3, 5, 7, 8, 9, 10]
                quote: false
        - name: max_wind_gust_mps_qn3
          description: placeholder
          data_type: float
        - name: mean_wind_velocity_mps_qn3
          description: placeholder
          data_type: float
        - name: precipitation_heigt_mm_qn4
          description: placeholder
          data_type: float
        - name: precipitation_type_qn4
          description: placeholder
          data_type: integer
          tests:
            - accepted_values:
                values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
                quote: false
        - name: sunshine_duration_h_qn4
          description: placeholder
          data_type: float
        - name: snow_depth_cm_qn4
          description: placeholder
          data_type: integer
        - name: mean_cloud_coverage_qn4
          description: placeholder
          data_type: string
        - name: mean_vapour_pressure_hpa_qn4
          description: placeholder
          data_type: float
        - name: mean_pressure_hpa_qn4
          description: placeholder
          data_type: float
        - name: mean_temperature_2m_c_qn4
          description: placeholder
          data_type: float
        - name: mean_rel_humidity_qn4
          description: placeholder
          data_type: float
        - name: max_temperature_2m_c_qn4
          description: placeholder
          data_type: float
        - name: min_temperature_2m_c_qn4
          description: placeholder
          data_type: float
        - name: mean_temperature_5cm_c_qn4
          description: placeholder
          data_type: float