
version: 1

sources:
    - name: staging
      #For bigquery:
      database: dtc-de-zoomcamp-376519
      schema: temperatures

      tables:
        - name: temperatures_all
         # freshness:
           # error_after: {count: 6, period: hour}

models:


    - name: stg_green_rides
      description: >
        Trip made by green taxis, also known as boro taxis and street-hail liveries.
        Green taxis may respond to street hails,but only in the areas indicated in green on the
        map (i.e. above W 110 St/E 96th St in Manhattan and in the boroughs).
        The records were collected and provided to the NYC Taxi and Limousine Commission (TLC) by
        technology service providers. 
      columns:
        - name: measurement_id 
          description: placeholder
          data_type: string
          tests:
            - unique:
                severity: warn
            - not_null:
                severity: warn
        - name: station_id
          description: placeholder
          data_type: string
          tests:
            - not_null:
                severity: warn
        - name: dt_measurement
          description: placeholder
          data_type: timestamp
          tests:
            - not_null:
                severity: warn
        - name: quality_niveau_3
          description: placeholder
          data_type: integer
          tests:
            - accepted_values:
                values: [1, 2, 3, 5, 7, 8, 9, 10]
                quote: false
        - name: quality_niveau_4
          description: placeholder
          data_type: integer
          tests:
            - accepted_values:
                values: [1, 2, 3, 5, 7, 8, 9, 10]
                quote: false
        - name: max_wind_gust_mps_qn3
          description: placeholder
          data_type: float
        - name: mean_wind_velocity_mps_qn3
          description: placeholder
          data_type: float
        - name: precipitation_heigt_mm_qn4
          description: placeholder
          data_type: float
        - name: precipitation_type_qn4
          description: placeholder
          data_type: integer
          tests:
            - accepted_values:
                values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
                quote: false
        - name: sunshine_duration_h_qn4
          description: placeholder
          data_type: integer
        - name: snow_depth_cm_qn4
          description: placeholder
          data_type: integer
        - name: mean_cloud_coverage_qn4
          description: placeholder
          data_type: string
        - name: mean_vapour_pressure_hpa_qn4
          description: placeholder
          data_type: float
        - name: mean_pressure_hpa_qn4
          description: placeholder
          data_type: float
        - name: mean_temperature_2m_c_qn4
          description: placeholder
          data_type: float
        - name: mean_rel_humidity_qn4
          description: placeholder
          data_type: float
        - name: max_temperature_2m_c_qn4
          description: placeholder
          data_type: float
        - name: min_temperature_2m_c_qn4
          description: placeholder
          data_type: float
        - name: mean_temperature_5cm_c_qn4
          description: placeholder
          data_type: float