version: 2

sources:
    - name: core
      #For bigquery:
      database: dtc-de-zoomcamp-376519
      schema: weather

      tables:
        - name: metadata_geo
        - name: metadata_operator
         # freshness:
           # error_after: {count: 6, period: hour}

models:
  - name: dim_geo
    description: >
      List of geographical locations of weather stations. Stations changed locations over time, this table reflects these scenarios
    columns:
      - name: station_id
        description: A code indicating the weather-station at which the measurements took place.
        data_type: string
      - name: station_height_m
        description: Height in meters of the weather-station relative to sea level at the time of measurement.
        data_type: int
      - name: latitude
        description: Geographical latitude of the weather-station at the time of measurement.
        data_type: string
      - name: longitude
        description: Geographical longitude of the weather-station at the time of measurement.
        data_type: string
      - name: dt_geo_start
        data_type: timestamp
        description: > 
          Begin of time period. Either the weather.        
      - name: dt_geo_end
        data_type: timestamp
        description: > 
          End of time period. 
          If null then the weather-station is currently operating under the selected geographical configuration.
          If not null then something changed and the weather-station is currently not operating under the selected geographical configuration.
      - name: station_name
        description: The weather-stations' name at the time of measurement.
        data_type: string
  - name: dim_operator
    description: >
      List of operators of weather stations. Stations changed operators over time, this table reflects these scenarios.
  - name: fact_measurements
    description: >
      Mean daily measurements.
      Table contains records of daily measurements. Values are totals, mean-averages, minima and maxima.
      Each measurement has a corresponding quality level (qn3, qn4), with a value of  
    columns:
      - name: measurement_id
        description: Primary key for this table, generated with a concatenation of station_id+dt_measurement
        data_type: string
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
      - name: station_id
        description: A code indicating the weather-station at which the measurements took place 
        data_type: string
        tests:
          - not_null:
              severity: warn
          - relationships:
              to: ref('dim_geo')
              field: station_id
              severity: warn
          - relationships:
              to: ref('dim_operator')
              field: station_id
              severity: warn
      - name: dt_measurement_utc
        description: >
          The time and date at which the measurement was recorded. 
          Some earlier measurements were done manually, so this timestamp may not be perfectly accurate.
        data_type: timestamp
        tests:
          - not_null:
                severity: warn
      - name: station_name
        description: The weather-stations' name at the time of measurement.
        data_type: string
      - name: operator_name
        description: The name of the entity operating the weather-station at the time of measurement.
        data_type: string
      - name: station_height_m
        description: Height in meters of the weather-station relative to sea level at the time of measurement.
        data_type: float
      - name: latitude
        description: Geographical latitude of the weather-station at the time of measurement.
        data_type: string
      - name: longitude
        description: Geographical longitude of the weather-station at the time of measurement.
        data_type: string
      - name: quality_niveau_3
        description: > 
          Quality level of wind-related measurements. 
          "{{ doc('quality_level') }}"
        data_type: integer
        tests:
          - accepted_values:
              values: [1, 2, 3, 5, 7, 8, 9, 10]
              quote: false
      - name: quality_niveau_4
        description: >
          Quality level of non wind-related measurements (temperature, sunshine, snow, (vapour)pressure) 
          "{{ doc('quality_level') }}"
        data_type: integer
        tests:
          - accepted_values:
              values: [1, 2, 3, 5, 7, 8, 9, 10]
              quote: false
      - name: max_wind_gust_mps_qn3
        description: Daily maximum of wind gust velocity in meters per second.
        data_type: float
      - name: mean_wind_velocity_mps_qn3
        description: Daily mean of wind gust velocity in meters per second.
        data_type: float
      - name: precipitation_heigt_mm_qn4
        description: Daily precipitation height in millimeters.
        data_type: float
      - name: precipitation_type_qn4
        description: "{{ doc('precipitation') }}"
        data_type: integer
        tests:
          - accepted_values:
              values: [0, 1, 4, 6, 7, 8, 9]
              quote: false
      - name: sunshine_duration_h_qn4
        description: Sum of direct sunlight time in hours from dusk until dawn.  
        data_type: float
      - name: snow_depth_cm_qn4
        description: Max snow depth in centimeters. 
        data_type: integer
      - name: mean_cloud_coverage_qn4
        description: Mean cloud coverage. Reported in fractions, e.g. "1/8"
        data_type: string
      - name: mean_vapour_pressure_hpa_qn4
        description: Mean vapour pressure in hPa.
        data_type: float
      - name: mean_pressure_hpa_qn4
        description: Mean atmospheric pressure in hPa.
        data_type: float
      - name: mean_temperature_2m_c_qn4
        description: Daily mean temperature at 2 meters above ground at the weather-station.
        data_type: float
      - name: mean_rel_humidity_qn4
        description: Daily mean humidity at 2 meters above ground at the weather-station.
        data_type: float
      - name: max_temperature_2m_c_qn4
        description: Daily maximum temperature at 2 meters above ground at the weather-station.
        data_type: float
      - name: min_temperature_2m_c_qn4
        description: Daily minimum temperature at 2 meters above ground at the weather-station.
        data_type: float
      - name: mean_temperature_5cm_c_qn4
        description: Daily mean temperature at 5 centimeters above ground at the weather-station.
        data_type: float